AWSTemplateFormatVersion: 2010-09-09

Parameters:

  HyP3URL:
    Type: String

  EDLUsername:
    Type: String

  EDLPassword:
    Type: String

Resources:
  ProductBucket:
    Type: AWS::S3::Bucket

  SubscriptionTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: subscription_name
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: subscription_name
          AttributeType: S
  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: subscription_name
          KeyType: HASH
        - AttributeName: product_id
          KeyType: RANGE
      AttributeDefinitions:
        - AttributeName: subscription_name
          AttributeType: S
        - AttributeName: product_id
          AttributeType: S
  Watcher:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: watcher/cloudformation.yml
      Parameters:
        HyP3_URL: !Ref HyP3URL
        EDLUsername: !Ref EDLUsername
        EDLPassword: !Ref EDLPassword