AWSTemplateFormatVersion: 2010-09-09

Parameters:

  HyP3URL:
    Type: String

  EDLUsername:
    Type: String

  EDLPassword:
    Type: String

Resources:
  ProductBucket:
    Type: AWS::S3::Bucket

  EventTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S

  ProductTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: event_id
          KeyType: HASH
        - AttributeName: product_id
          KeyType: RANGE
      GlobalSecondaryIndexes:
        - IndexName: status_code
          KeySchema:
            - AttributeName: status_code
              KeyType: HASH
            - AttributeName: processing_date
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
      AttributeDefinitions:
        - AttributeName: event_id
          AttributeType: S
        - AttributeName: product_id
          AttributeType: S
        - AttributeName: status_code
          AttributeType: S
        - AttributeName: processing_date
          AttributeType: S

  FindNew:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: find_new/cloudformation.yml
      Parameters:
        HyP3URL: !Ref HyP3URL
        EventTable: !Ref EventTable
        ProductTable: !Ref ProductTable
        EDLUsername: !Ref EDLUsername
        EDLPassword: !Ref EDLPassword
  Api:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: api/cloudformation.yml
      Parameters:
        EventTable: !Ref EventTable
        ProductTable: !Ref ProductTable
  HarvestProducts:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: harvest_products/cloudformation.yml
      Parameters:
        ProductBucket: !Ref ProductBucket
        HyP3URL: !Ref HyP3URL
        ProductTable: !Ref ProductTable
        EDLUsername: !Ref EDLUsername
        EDLPassword: !Ref EDLPassword
