name: Write release and finish

on:
  push:
    tags:
      - v*


jobs:
  finish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Create Release
        uses: docker://antonyurchenko/git-release:latest
        env:
          GITHUB_TOKEN: ${{ secrets.TOOLS_BOT_PAK }}
          ALLOW_TAG_PREFIX: "true"
          RELEASE_NAME_PREFIX: "HyP3 Event Monitoring "
