name: Static code analysis

on: push

jobs:
  call-flake8-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-flake8.yml@v0.11.2
    with:
      local_package_names: api,database,find_new,harvest_products

  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-all.txt
      - run: |
          cfn-lint --info --ignore-checks W3002 --template cloudformation.yml **/cloudformation.yml
