name: Static code analysis

on: push

jobs:
  call-ruff-workflow:
    # Docs: https://github.com/ASFHyP3/actions
    uses: ASFHyP3/actions/.github/workflows/reusable-ruff.yml@v0.14.0

  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.12
      - run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements-all.txt
      - run: |
          cfn-lint --info --ignore-checks W3002 --template cloudformation.yml **/cloudformation.yml
