name: Static code analysis

on: push

jobs:
  call-flake8-workflow:
    uses: ASFHyP3/actions/.github/workflows/reusable-flake8.yml@main
    with:
      local_package_namkes: api,database,find_new,harvest_products

  cfn-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: scottbrenner/cfn-lint-action@master
        with:
          args: "--ignore-checks W3002 --template cloudformation.yml **/cloudformation.yml"
